version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: udemy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udemy
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: udemy-redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: udemy-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:latest
    container_name: udemy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./udemy-backend
    container_name: udemy-backend
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - ollama
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build: ./udemy-frontend
    container_name: udemy-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
  es_data:
  ollama_data: