# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/udemy?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=141512

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=30s

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Ollama
# spring.ai.ollama.base-url=http://localhost:11434
spring.ai.openai.api-key=${AI_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
# VNPay
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:5173/payment-result

# Frontend
app.frontend-url=http://localhost:5173